#!/usr/bin/env python3
"""make_cards.py — 由 data/valuation_<AS_OF>.json（模型输出）+ 下方各卡的判断字段，生成 8 个 decision_card.json。
数字只来自模型输出，不手抄；判断字段（信号、裁决、kill criteria）在此集中登记，便于 Checker 对照 decision_card.md。
"""
from __future__ import annotations

import json
from pathlib import Path

AS_OF = "2026-09-28"
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
VAL = json.loads((HERE / "data" / f"valuation_{AS_OF}.json").read_text(encoding="utf-8"))
SNAP = json.loads((HERE / "data" / f"snapshot_{AS_OF}.json").read_text(encoding="utf-8"))

COMMON = {
    "as_of": AS_OF, "pipeline_version": "lean-6module-v1.1", "weights_version": "none", "run_date": AS_OF,
    "batch": "pelosi_book_2026-09-28", "run_type": "first_dossier", "refresh_of": None, "status": "DECISION_DRAFT",
    "clean": False, "clean_blocked_reason": "Checker != Runner (PROTOCOL §3) not met: single agent, self-checked only",
    "price_sources": ["yahoo_chart_api", "nasdaq_historical_api"], "price_date": "2026-09-25",
    "valuation_method": "batch valuation_model.py: 10y cash-flow IRR incl. interim payouts p*OE; library MSFT-formula IRR reported alongside",
    "idea_source": "user-supplied Pelosi holdings table (lead only; not evidence)",
}

CARDS = {
    "UBER": dict(
        context_label="structural_decline_trap", business_verdict="good",
        module_signals={"M1": 1, "M2": 0, "M3": 1, "M4": 2, "M5": -1, "M6": 2},
        new_money_verdict="WATCH", runner_proposed_verdict="STARTER", runner_proposed_size_pct=3,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=10,
        zones={"starter": "<= 86.63 (base >=10%)", "add": "<= 74.16 (base >=12%) AND K-U1 green",
               "hold": "86.63 - 101.71", "no_chase": "> 101.71", "avoid": "> 175.51"},
        binding_constraint="(1) independent Checker not yet run (process); (2) speed of AV disintermediation (judgement). NOT price.",
        completeness_pct=65, share_count_yoy_pct={"basic": -2.61, "diluted": -3.55}, sbc_to_revenue_pct=3.5,
        owner_earnings_ttm_usd_b={"fcf": 10.12, "fcf_minus_sbc": 8.18, "oe_band": [5.7, 8.18]},
        kill_criteria=["K-U1 Mobility GB cc growth <10% two straight quarters OR >=2 more top-10 US cities go AV-direct -> green",
                       "K-U2 AV spend >$3B/yr with no volume/revenue disclosure -> yellow",
                       "K-U3 buybacks < SBC (share count stops falling) -> green",
                       "K-U4 Mobility segment profit/GB falls two straight quarters -> green (7.28% -> 7.64%)",
                       "K-U5 driver-classification regulation >1pp GB cost -> unquantified"],
        next_monitor_event="Q3 2026 earnings (~early Nov 2026): Mobility GB cc, segment profit/GB, AV trips, buybacks",
        insider_activity="Form 4: CEO Khosrowshahi P 141,000 @ $70.96 (~$10.0M, filed 2026-09-10); President/COO Macdonald P 70,000 @ $75.65-76.44 (~$5.3M, filed 2026-09-08)",
        factor_check="not AI-capex; negative exposure to AV success; offsets rather than doubles the BTC/GOOGL/NBIS factor (note GOOGL/Waymo is the AV counterparty)",
        pelosi_position_lead="200 calls $50 strike exp 2027-03-19, trade 2026-05-29, disclosed 2026-06-23 (secondary)",
        open_items=["O-U1 AV >$10B plan primary quantification", "O-U2 Waymo contract terms", "O-U3 2026-09-15 notes amount",
                    "O-U4 remaining buyback authorization", "O-U5 EU platform-work directive cost"],
        sources=[("UBER-8K-Q2", "2026-08-05", "https://www.sec.gov/Archives/edgar/data/1543151/000154315126000027/uberq226earningspressrelea.htm"),
                 ("UBER-10Q-Q2", "2026-08-05", "https://www.sec.gov/Archives/edgar/data/1543151/000154315126000032/uber-20260630.htm"),
                 ("UBER-F4-DK", "2026-09-10", "https://www.sec.gov/Archives/edgar/data/1543151/000118423726000008/primarydocument.xml"),
                 ("UBER-F4-AM", "2026-09-08", "https://www.sec.gov/Archives/edgar/data/1543151/000207176126000011/primarydocument.xml"),
                 ("UBER-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001543151.json")]),
    "AB": dict(
        context_label="yield_or_balance_sheet_trap", business_verdict="good",
        module_signals={"M1": 1, "M2": 0, "M3": 0, "M4": 1, "M5": 0, "M6": 2},
        new_money_verdict="WATCH", runner_proposed_verdict="STARTER", runner_proposed_size_pct=3,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=5,
        zones={"starter": "<= 43.49 (base >=10%)", "add": "<= 38.26 (base >=12%) AND distribution TTM >= $3.20",
               "hold": "43.49 - 49.72", "no_chase": "> 49.72", "avoid": "> 65.32"},
        binding_constraint="(1) independent Checker not yet run; (2) holding wrapper: PTP, 100% ECI -> 37% withholding for foreign holders (user plans NRA status from 2028). NOT price.",
        completeness_pct=62, share_count_yoy_pct={"units_note": "AB Holding units 110.5M (2024-12) -> 93.1M (2026-06) reflect Equitable restructuring, not buybacks"},
        sbc_to_revenue_pct=None,
        owner_earnings_ttm_usd_b={"distributions_per_unit_ttm": 3.47, "distribution_yield_pct": 9.70},
        kill_criteria=["K-AB1 TTM distribution < $2.90 without a >15% market drawdown -> green ($3.47)",
                       "K-AB2 active-equity net outflows > $15B in a quarter -> yellow (~$11B in Q2)",
                       "K-AB3 markdowns / gating in AB private-credit vehicles -> green (none in 10-Q)",
                       "K-AB4 GP retains cash instead of distributing Available Cash Flow -> green",
                       "K-AB5 adjusted operating margin < 30% -> green (33.0%)",
                       "K-AB6 holder tax status: 37% withholding once NRA -> known, priced (base IRR +10.4% after withholding)"],
        next_monitor_event="Q3 2026 earnings (~late Oct 2026) and monthly AUM release (~10th of each month)",
        insider_activity=None,
        factor_check="NOT AI: market beta / rates / active-management flows. The only genuinely off-factor name among Pelosi's 13",
        pelosi_position_lead="AB Holding units purchase, trade 2026-01-16 (close $40.17), $1-5M (secondary); table says 25,000 units",
        open_items=["O-AB1 private credit AUM and fee share (10-Q silent)", "O-AB2 fee-rate trend by channel",
                    "O-AB3 user-specific PTP tax treatment (CPA; K-1, §1446(a)/(f))", "O-AB4 CEO transition 2027-03-31 (Erzan) strategy"],
        sources=[("AB-8K-Q2", "2026-07-28", "https://www.sec.gov/Archives/edgar/data/1109448/000110944826000194/a2q26earningsrelease.htm"),
                 ("AB-10Q-Q2", "2026-07-31", "https://www.sec.gov/Archives/edgar/data/1109448/000110944826000197/ab-20260630.htm"),
                 ("AB-8K-AUM-AUG", "2026-09-10", "https://www.sec.gov/Archives/edgar/data/1109448/000110944826000278/ex9901ab2026augustaumrelea.htm"),
                 ("AB-8K-CEO", "2026-09-25", "https://www.sec.gov/Archives/edgar/data/1109448/000110944826000281/ex9901ableadershipchanges9.htm"),
                 ("ABH-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0000825313.json")]),
    "VST": dict(
        context_label="cyclical_inflection", business_verdict="good",
        module_signals={"M1": 1, "M2": 1, "M3": 1, "M4": 1, "M5": -1, "M6": 1},
        new_money_verdict="WATCH", runner_proposed_verdict="STARTER", runner_proposed_size_pct=3,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=8,
        zones={"starter": "<= 142.18 (base >=10%)", "add": "<= 123.61 (base >=12%) AND FCFbG guide intact",
               "hold": "142.18 - 164.49", "no_chase": "> 164.49", "avoid": "> 269.59"},
        binding_constraint="(1) independent Checker not yet run; (2) leverage + post-2027 power-price regime (hedges 94% 2027, 72% 2028). NOT price.",
        completeness_pct=62, share_count_yoy_pct={"basic": -0.75, "diluted": -1.82}, sbc_to_revenue_pct=0.7,
        owner_earnings_ttm_usd_b={"fcfbg_2026_guide_mid": 4.325, "oe_after_pref_and_sbc": 4.0},
        kill_criteria=["K-V1 FCFbG guidance cut >10% -> green (reaffirmed 2026-08-07)",
                       "K-V2 (debt $19.6B + AR financing/forward repurchase $0.9B + preferred $2.48B) / 2026 EBITDA guide mid $7.2B > 3.5x -> green now (~3.2x); ~3.4x est. after Cogentrix ($2.3B cash + $1.5B assumed debt)",
                       "K-V3 2028 hedges roll at materially lower prices / ERCOT forward keeps falling -> yellow",
                       "K-V4 adverse FERC co-location rule or PJM price-collar extension -> yellow",
                       "K-V5 extended nuclear outage -> green",
                       "K-V6 45U nuclear PTC repeal/curtailment before 2032 -> green"],
        next_monitor_event="Q3 2026 earnings (~early Nov 2026); Cogentrix closing; 2027 guidance",
        insider_activity=None,
        factor_check="PARTIAL AI: base cash flow (hedged generation, retail, 45U floor) is not AI-dependent, but the growth leg (Meta PPAs, Helix) is the same AI factor as BTC/GOOGL/NBIS -> yellow",
        pelosi_position_lead="LEAPS $50 strike (table; not verified this run)",
        open_items=["O-V1 hedged price levels for 2027-28", "O-V2 Cogentrix financing mix and close date",
                    "O-V3 use of Sept-2026 $1.5B junior subordinated notes", "O-V4 Meta PPA pricing"],
        sources=[("VST-8K-Q2", "2026-08-07", "https://www.sec.gov/Archives/edgar/data/1692819/000169281926000017/vistra-20260630xearningsre.htm"),
                 ("VST-10Q-Q2", "2026-08-10", "https://www.sec.gov/Archives/edgar/data/1692819/000169281926000019/vistra-20260630.htm"),
                 ("VST-8K-0924", "2026-09-24", "https://www.sec.gov/Archives/edgar/data/1692819/000114036126037577/ef20082680_8k.htm"),
                 ("VST-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001692819.json")]),
    "AVGO": dict(
        context_label="exceptional_bottleneck", business_verdict="exceptional",
        module_signals={"M1": 1, "M2": 2, "M3": 1, "M4": 1, "M5": -1, "M6": -2},
        new_money_verdict="WATCH", runner_proposed_verdict="WATCH", runner_proposed_size_pct=0,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=12,
        zones={"starter": "<= 220.99 (base >=8%)", "add": "<= 187.97 (base >=10%)", "hold": None,
               "no_chase": "> 220.99 (current price is here)", "avoid": "> 484.11"},
        binding_constraint="PRICE. Base IRR +2.5%; the stock would need to fall 37% to reach the 8% line.",
        completeness_pct=60, share_count_yoy_pct={"basic": 1.10, "diluted": 0.56}, sbc_to_revenue_pct=9.5,
        owner_earnings_ttm_usd_b={"fcf": 39.40, "fcf_minus_sbc": 30.92, "q4_guided_run_rate_oe": 52.0},
        kill_criteria=["K-A1 AI semiconductor revenue declines QoQ two straight quarters -> green (Q4 guide $21.7B vs $16.7B)",
                       "K-A2 consolidated gross margin <70% with no operating-margin offset -> yellow (Q4 guide ~73%, down from 78%)",
                       "K-A3 disclosed single-customer concentration >30% -> unknown (10-Q silent)",
                       "K-A4 inventory keeps doubling faster than revenue -> yellow ($2.27B -> $4.52B in 3 quarters)"],
        next_monitor_event="Q4 FY26 earnings (~mid-Dec 2026): AI revenue vs $21.7B guide, gross margin, FY27 AI commentary",
        insider_activity=None, factor_check="AI capex factor (same as BTC/GOOGL/NBIS) -> doubles, not diversifies",
        pelosi_position_lead="shares, 20,000 exercised 2025-06 (table; not verified this run)",
        open_items=["O-A1 customer concentration", "O-A2 RPO composition by customer/product", "O-A3 VMware renewal cliff"],
        sources=[("AVGO-8K-Q3", "2026-09-02", "https://www.sec.gov/Archives/edgar/data/1730168/000173016826000076/avgo-08022026x8kxex99.htm"),
                 ("AVGO-10Q-Q3", "2026-09-10", "https://www.sec.gov/Archives/edgar/data/1730168/000173016826000080/avgo-20260802.htm"),
                 ("AVGO-8K-APPLE", "2026-07-06", "https://www.sec.gov/Archives/edgar/data/1730168/000119312526295589/d84378d8k.htm"),
                 ("AVGO-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001730168.json")]),
    "BE": dict(
        context_label="exceptional_bottleneck", business_verdict="good",
        module_signals={"M1": 1, "M2": 2, "M3": 0, "M4": 1, "M5": -1, "M6": -2},
        new_money_verdict="WATCH", runner_proposed_verdict="WATCH", runner_proposed_size_pct=0,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=5,
        zones={"starter": "<= 178.80 (base >=8%)", "add": "<= 148.82 (base >=10%)", "hold": None,
               "no_chase": "> 178.80 (current price is here)", "avoid": "> 460.18"},
        binding_constraint="PRICE. Base IRR +2.9% even with 25%/yr owner-earnings growth for 10 years.",
        completeness_pct=55, share_count_yoy_pct={"basic": 23.5, "diluted": 39.0, "period": "Q2'26 vs Q2'25 (8-K weighted shares)"},
        sbc_to_revenue_pct=6.1,
        owner_earnings_ttm_usd_b={"fcf_ttm_est": 0.62, "fcf_minus_sbc_ttm_est": 0.44, "fy26_guide_based_oe": 0.67},
        kill_criteria=["K-B1 non-GAAP gross margin <30% two quarters -> green (34.3%)",
                       "K-B2 FY revenue guide cut -> green (raised to $3.9-4.2B)",
                       "K-B3 disclosed scandium/supply constraint (Hunterbrook 2026-07-08 claim) -> yellow (company denies)",
                       "K-B4 share count +10%/yr continues -> red (+23.5% basic YoY)"],
        next_monitor_event="Q3 2026 earnings (~late Oct 2026)",
        insider_activity=None, factor_check="AI capex factor -> doubles",
        pelosi_position_lead="15,000 shares (7/24 @ $184.89, 7/28 @ $166.84) + 200 calls $100 exp 2027-06-17; disclosed ~2026-08-24 (secondary)",
        open_items=["O-B1 backlog primary figure", "O-B2 Brookfield financing terms", "O-B3 scandium supply chain"],
        sources=[("BE-8K-Q2", "2026-07-28", "https://www.sec.gov/Archives/edgar/data/1664703/000162828026050150/ex991_q226financialresults.htm"),
                 ("BE-8K-0709", "2026-07-09", "https://www.sec.gov/Archives/edgar/data/1664703/000162828026047734/be-20260709.htm"),
                 ("BE-8K-0413", "2026-04-13", "https://www.sec.gov/Archives/edgar/data/1664703/000162828026024896/be-20260413.htm"),
                 ("BE-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001664703.json")]),
    "INTC": dict(
        context_label="turnaround", business_verdict="uncertain",
        module_signals={"M1": 1, "M2": 1, "M3": -1, "M4": -1, "M5": -1, "M6": -2},
        new_money_verdict="WATCH", runner_proposed_verdict="WATCH", runner_proposed_size_pct=0,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=5,
        zones={"starter": "<= 47.33 (base >=8%)", "add": "<= 39.39 (base >=10%)", "hold": None,
               "no_chase": "> 47.33", "avoid": "> 115.69 (current price is here: even the bull case < 8%)"},
        binding_constraint="PRICE. Base IRR -1.8%; bull +7.3% -- no scenario clears the hurdle at $123.",
        completeness_pct=55, share_count_yoy_pct={"basic": 16.82, "post_aug_offering_est": 21.0}, sbc_to_revenue_pct=4.2,
        owner_earnings_ttm_usd_b={"fcf": 2.83, "fcf_minus_sbc": 0.44, "adjusted_fcf_q2": -8.42},
        kill_criteria=["K-I1 named external 14A customer commitment by 2027-06 -> positive trigger, not yet",
                       "K-I2 another equity raise within 12 months -> watch",
                       "K-I3 non-GAAP gross margin <38% -> green (41.8%)",
                       "K-I4 foundry ownership <51% (USG warrant trigger, 241M shares) -> green"],
        next_monitor_event="Q3 2026 earnings (~late Oct 2026)",
        insider_activity=None, factor_check="AI capex + US industrial-policy factor -> doubles",
        pelosi_position_lead="10,000 shares 2026-07-24 @ $92.32 + 200 calls $50 exp 2027-03-19 (trade 2026-05-29) (secondary)",
        open_items=["O-I1 escrowed 143M shares release schedule", "O-I2 2026 gross/net capex guide", "O-I3 14A customer pipeline"],
        sources=[("INTC-8K-Q2", "2026-07-23", "https://www.sec.gov/Archives/edgar/data/50863/000005086326000155/q226earningsrelease.htm"),
                 ("INTC-424B5", "2026-08-12", "https://www.sec.gov/Archives/edgar/data/50863/000119312526345221/d98483d424b5.htm"),
                 ("INTC-8K-0812", "2026-08-12", "https://www.sec.gov/Archives/edgar/data/50863/000119312526346806/d117670dex991.htm"),
                 ("INTC-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0000050863.json")]),
    "CRWD": dict(
        context_label="quality_compounder", business_verdict="good",
        module_signals={"M1": 1, "M2": 1, "M3": 1, "M4": -1, "M5": -1, "M6": -2},
        new_money_verdict="WATCH", runner_proposed_verdict="WATCH", runner_proposed_size_pct=0,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=8,
        zones={"starter": "<= 73.76 (base >=8%)", "add": "<= 61.40 (base >=10%)", "hold": None,
               "no_chase": "> 73.76", "avoid": "> 154.31 (current price is here: even the bull case < 8%)"},
        binding_constraint="PRICE. Base IRR -4.5%; bull +2.8%. P/S ~48x TTM.",
        completeness_pct=55, share_count_yoy_pct={"basic": 1.98, "diluted": 4.49}, sbc_to_revenue_pct=23.1,
        owner_earnings_ttm_usd_b={"fcf_company_def": 1.52, "sbc": 1.24, "fcf_minus_sbc": 0.28},
        kill_criteria=["K-C1 net new ARR growth turns negative YoY -> green (+51%)",
                       "K-C2 SBC/revenue not below 20% by FY28 -> yellow (23%)",
                       "K-C3 another platform-wide outage (2024-07-19 precedent) -> green"],
        next_monitor_event="Q3 FY27 earnings (~early Dec 2026)",
        insider_activity=None, factor_check="AI-security narrative factor; correlated with PANW (same-day low 2026-02-24)",
        pelosi_position_lead="shares ~6% (table; not found in 2026 PTR search)",
        open_items=["O-C1 GRR/NRR exact figures", "O-C2 Falcon Flex economics"],
        sources=[("CRWD-8K-Q2", "2026-08-26", "https://www.sec.gov/Archives/edgar/data/1535527/000153552726000029/crwd-20260826xex991.htm"),
                 ("CRWD-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001535527.json")]),
    "PANW": dict(
        context_label="quality_compounder", business_verdict="good",
        module_signals={"M1": 1, "M2": 1, "M3": 1, "M4": 0, "M5": -1, "M6": -2},
        new_money_verdict="WATCH", runner_proposed_verdict="WATCH", runner_proposed_size_pct=0,
        existing_position_verdict="HOLD", suggested_initial_size_pct=0, suggested_max_size_pct=8,
        zones={"starter": "<= 150.06 (base >=8%)", "add": "<= 124.90 (base >=10%)", "hold": None,
               "no_chase": "> 150.06", "avoid": "> 285.52 (current price is here: even the bull case < 8%)"},
        binding_constraint="PRICE. Base IRR -1.4%; bull +5.1%. ~90x FY27 non-GAAP EPS guide.",
        completeness_pct=55, share_count_yoy_pct={"basic": 20.45, "diluted": 13.30, "period": "Q3 FY26 vs Q3 FY25"},
        sbc_to_revenue_pct=15.5,
        owner_earnings_ttm_usd_b={"fcf": 4.11, "sbc": 1.77, "fcf_minus_sbc": 2.34},
        kill_criteria=["K-P1 organic (ex-CyberArk) NGS ARR growth <20% -> unknown (not split out)",
                       "K-P2 adjusted FCF margin <36% -> green (FY27 guide 38%)",
                       "K-P3 another stock-funded acquisition >5% dilution -> watch"],
        next_monitor_event="Q1 FY27 earnings (~mid-Nov 2026)",
        insider_activity=None, factor_check="AI-security narrative factor; correlated with CRWD",
        pelosi_position_lead="shares, 14,000 exercised 2024-12 (table; not verified this run)",
        open_items=["O-P1 organic vs acquired ARR split", "O-P2 CyberArk integration costs"],
        sources=[("PANW-8K-Q4", "2026-09-01", "https://www.sec.gov/Archives/edgar/data/1327567/000132756726000019/ex991q426earningsrelease.htm"),
                 ("PANW-10K-FY26", "2026-09-10", "https://www.sec.gov/Archives/edgar/data/1327567/000132756726000023/panw-20260731.htm"),
                 ("PANW-XBRL", AS_OF, "https://data.sec.gov/api/xbrl/companyfacts/CIK0001327567.json")]),
}


def main():
    for tk, c in CARDS.items():
        v = VAL["tickers"][tk]
        man = json.loads((ROOT / tk.lower() / AS_OF / "freshness.json").read_text(encoding="utf-8"))
        lf = {f["field"]: f for f in man["live_fields"]}
        card = {"ticker": tk, **COMMON,
                "as_of_price": v["price"],
                "as_of_market_cap": lf["market_cap"]["value"],
                "shares_out_m_for_market_cap": lf["shares_out"]["value"],
                "valuation_shares_m": v["shares_m"], "valuation_market_cap_usd_b": v["mcap_b"],
                "wk52_high": lf["52wk_high"]["value"], "wk52_low": lf["52wk_low"]["value"],
                **{k: c[k] for k in ("context_label", "module_signals", "business_verdict", "new_money_verdict",
                                     "runner_proposed_verdict", "runner_proposed_size_pct", "existing_position_verdict",
                                     "suggested_initial_size_pct", "suggested_max_size_pct")},
                "buy_below_price": v["hurdle_prices"]["8pct"],
                "hurdle_prices": v["hurdle_prices"],
                "zones": c["zones"],
                "binding_constraint": c["binding_constraint"],
                "completeness_pct": c["completeness_pct"],
                "scenarios_10y": {k: {kk: s[kk] for kk in s if kk not in ("mode",)} | {"mode": s["mode"]}
                                  for k, s in v["scenarios"].items()},
                "share_count_yoy_pct": c["share_count_yoy_pct"], "sbc_to_revenue_pct": c["sbc_to_revenue_pct"],
                "owner_earnings_ttm_usd_b": c["owner_earnings_ttm_usd_b"],
                "kill_criteria": c["kill_criteria"], "next_monitor_event": c["next_monitor_event"],
                "insider_activity": c["insider_activity"], "factor_check": c["factor_check"],
                "pelosi_position_lead": c["pelosi_position_lead"], "open_items": c["open_items"],
                "sources_used": [{"source_id": s, "public_date": d, "url": u} for s, d, u in c["sources"]]}
        if tk == "AB":
            card["base_irr_if_nra_from_2028"] = v.get("base_irr_if_nra_from_2028")
        out = ROOT / tk.lower() / AS_OF / "decision_card.json"
        out.write_text(json.dumps(card, indent=1, ensure_ascii=False), encoding="utf-8")
        print(tk, card["new_money_verdict"], "proposed", card["runner_proposed_verdict"],
              "base", v["scenarios"]["base"]["irr"], "bb", card["buy_below_price"])


if __name__ == "__main__":
    main()
