"""One-shot script: add ~30 China companies to china_companies.csv based on Phase 3 research."""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV = ROOT / "career-thesis" / "2026-ai-healthcare" / "data" / "china_companies.csv"

# Header matches china_companies.csv (already created in Phase 3 lock)
# Columns: name,name_zh,segment,subsegment,founded_year,hq_city,status,listing,
#   latest_valuation_usd_m,total_funding_usd_m,latest_round_date,latest_round_type,
#   revenue_usd_m,revenue_yoy_pct,payer_type,business_model,moat_type,
#   founders_phd_count,founders_background,founders_returnee,tech_dna,hardware_component,
#   us_counterpart,overseas_status,overseas_target_regions,entry_paths,nick_notes,data_as_of

ROWS = [
    # S5 Medical Imaging AI (Nick's main interest)
    {
        "name": "United Imaging Intelligence", "name_zh": "联影智能",
        "segment": "S5", "subsegment": "multimodal_imaging_ai",
        "founded_year": "2017", "hq_city": "Shanghai", "status": "private",
        "listing": "preparing_IPO_planned",
        "latest_valuation_usd_m": "1400", "total_funding_usd_m": "140",  # 100亿 RMB val + 10亿 raise
        "latest_round_date": "2025-06", "latest_round_type": "A",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital", "business_model": "per_alert_subscription_plus_oem",
        "moat_type": "integration", "founders_phd_count": "2",
        "founders_background": "from 联影集团 spinout, deep imaging algorithm + clinical team",
        "founders_returnee": "1",  # partial
        "tech_dna": "hybrid", "hardware_component": "embedded_in_device",
        "us_counterpart": "Aidoc / Viz.ai / Annalise.ai",
        "overseas_status": "planning",
        "overseas_target_regions": "SEA, MEA",
        "entry_paths": "direct hire 上海; 联影集团内部 transfer; international biz BD;"
                       " ⭐ Nick MAIN candidate A — algorithm engineer / research scientist / clinical PM",
        "nick_notes": "16 NMPA 三类证 行业第一 (含联影集团 + 联影医疗 + 联影智融). $100亿 估值 Jun2025. PA imaging 背景对口 + 上海 HQ 兼容北京家族业务",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "United Imaging Healthcare", "name_zh": "联影医疗",
        "segment": "S5", "subsegment": "imaging_device_oem_parent",
        "founded_year": "2011", "hq_city": "Shanghai", "status": "public",
        "listing": "A_share_688271_SSE_STAR",
        "latest_valuation_usd_m": "15000", "total_funding_usd_m": "",
        "latest_round_date": "2022-08", "latest_round_type": "IPO",
        "revenue_usd_m": "1500", "revenue_yoy_pct": "20",
        "payer_type": "hospital", "business_model": "device_sales_plus_service",
        "moat_type": "scale_plus_integration", "founders_phd_count": "1",
        "founders_background": "薛敏 PhD (United Imaging founder, ex-Siemens)",
        "founders_returnee": "1", "tech_dna": "hardware", "hardware_component": "embedded_in_device",
        "us_counterpart": "GE Healthcare / Siemens Healthineers / Philips (= GPS competitor)",
        "overseas_status": "active", "overseas_target_regions": "SEA, MEA, EU, LATAM",
        "entry_paths": "public-co hire 上海; international business 部门 ⭐ Nick MAIN candidate A2",
        "nick_notes": "联影集团母公司。A 股上市. 海外营收占比逐年提升. 是中国唯一全栈 imaging device 厂. 联影智能 + 联影智融 子公司",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Shukun Technology", "name_zh": "数坤科技",
        "segment": "S5", "subsegment": "cardiac_plus_neuro_imaging",
        "founded_year": "2017", "hq_city": "Beijing", "status": "private",
        "listing": "preparing_HK_IPO",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "305",
        "latest_round_date": "2023", "latest_round_type": "D",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital", "business_model": "per_study_fee",
        "moat_type": "regulatory_plus_clinical_partnerships", "founders_phd_count": "2",
        "founders_background": "马春娥 + 毛新生 (ex-IBM)",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "HeartFlow / Cleerly",
        "overseas_status": "planning", "overseas_target_regions": "SEA",
        "entry_paths": "direct hire 北京; preparing HK IPO 2025-2026",
        "nick_notes": "14 NMPA 三类证. 心脑血管 AI 头部. 据报 2025 可能盈利. 北京家族业务直接同城",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "InferVision", "name_zh": "推想医疗",
        "segment": "S5", "subsegment": "chest_ct_lung",
        "founded_year": "2015", "hq_city": "Beijing", "status": "private",
        "listing": "HK_IPO_withdrawn_2022_re_filing",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "200",
        "latest_round_date": "2022", "latest_round_type": "E",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital", "business_model": "per_study_subscription",
        "moat_type": "regulatory_plus_brand", "founders_phd_count": "1",
        "founders_background": "陈宽 PhD (Univ of Chicago)",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Aidoc",
        "overseas_status": "planning", "overseas_target_regions": "EU, SEA",
        "entry_paths": "direct hire 北京",
        "nick_notes": "13 NMPA 三类证. HK IPO 2022 withdrawn (中概股寒冬). 据报 2025 可能盈利. 红旗 1/6 (长期没新轮)",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Deepwise", "name_zh": "深睿医疗",
        "segment": "S5", "subsegment": "multi_modal_imaging",
        "founded_year": "2017", "hq_city": "Beijing", "status": "private",
        "listing": "private",
        "latest_valuation_usd_m": "350", "total_funding_usd_m": "180",
        "latest_round_date": "2024", "latest_round_type": "C+",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital", "business_model": "per_study_subscription",
        "moat_type": "regulatory", "founders_phd_count": "1",
        "founders_background": "乔昕 (ex-Philips imaging)",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Annalise.ai / Aidoc",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "direct hire 北京",
        "nick_notes": "14 NMPA 三类证. $25亿 RMB ~ $350M val. 创始人 ex-Philips 影像背景对口",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Airdoc", "name_zh": "鹰瞳科技",
        "segment": "S5", "subsegment": "retinal_imaging",
        "founded_year": "2015", "hq_city": "Beijing", "status": "public",
        "listing": "HK_2251_HK",
        "latest_valuation_usd_m": "400", "total_funding_usd_m": "150",
        "latest_round_date": "2021-11", "latest_round_type": "IPO",
        "revenue_usd_m": "30", "revenue_yoy_pct": "30",
        "payer_type": "patient_plus_insurer", "business_model": "per_scan_plus_screening_subscription",
        "moat_type": "regulatory_plus_brand", "founders_phd_count": "1",
        "founders_background": "张大磊 PhD (ex-Microsoft)",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "paired_device",
        "us_counterpart": "IDx-DR (US ophthalmology AI)",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 北京",
        "nick_notes": "眼底视网膜 AI 头部. HK 2021 IPO 后股价跌 70%+. 红旗 2/6 (估值倒挂 + 商业化不佳)",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Thorough Images", "name_zh": "透彻影像",
        "segment": "S5", "subsegment": "pathology_ai",
        "founded_year": "2017", "hq_city": "Beijing", "status": "private",
        "listing": "private",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "50",
        "latest_round_date": "2024", "latest_round_type": "C",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital_plus_pharma", "business_model": "per_specimen_plus_pharma",
        "moat_type": "regulatory_plus_data", "founders_phd_count": "1",
        "founders_background": "李欣 PhD",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "paired_device",
        "us_counterpart": "PathAI / Paige",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "direct hire 北京",
        "nick_notes": "中国病理 AI 头部. 比美国 PathAI/Paige 早期得多",
        "data_as_of": "2026-05-16",
    },

    # S3 Precision Medicine
    {
        "name": "MGI Tech", "name_zh": "华大智造",
        "segment": "S3", "subsegment": "ngs_sequencer_plus_lab_automation",
        "founded_year": "2016", "hq_city": "Shenzhen", "status": "public",
        "listing": "A_share_688114_SSE_STAR",
        "latest_valuation_usd_m": "3000", "total_funding_usd_m": "",
        "latest_round_date": "2022-09", "latest_round_type": "IPO",
        "revenue_usd_m": "150", "revenue_yoy_pct": "-9",  # H1 2025 base
        "payer_type": "lab_plus_research", "business_model": "device_sales_plus_consumables_plus_service",
        "moat_type": "scale_plus_IP", "founders_phd_count": "2",
        "founders_background": "汪建 + 王俊 (BGI co-founders); MGI 独立 2016",
        "founders_returnee": "1", "tech_dna": "hardware", "hardware_component": "embedded_in_device",
        "us_counterpart": "Illumina (sequencing rival) / 10x Genomics",
        "overseas_status": "active",
        "overseas_target_regions": "SEA, EU, LATAM, MEA, Africa - 76 countries",
        "entry_paths": "public-co hire 深圳; ⭐ international business 部门 — Nick MAIN candidate B"
                       " (MGI Americas + MGI Europe + MGI Latin America 都在 active hiring)",
        "nick_notes": "海外营收占比 33% (2025 H1 在手订单). 76 国覆盖, 1080+ 客户. 但 2025 H1 海外营收 YoY -9% (Trump 关税 + 中美摩擦). 最近卖出 US CGI 子公司 $50M 给瑞士 Swiss Rockets",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Burning Rock Biotech", "name_zh": "燃石医学",
        "segment": "S3", "subsegment": "oncology_ngs_panels",
        "founded_year": "2014", "hq_city": "Guangzhou", "status": "public",
        "listing": "NASDAQ_BNR_near_delisting_then_share_consolidation",
        "latest_valuation_usd_m": "300", "total_funding_usd_m": "470",
        "latest_round_date": "2020-06", "latest_round_type": "IPO",
        "revenue_usd_m": "55", "revenue_yoy_pct": "-10",
        "payer_type": "hospital_plus_patient_plus_pharma", "business_model": "per_test_plus_data",
        "moat_type": "regulatory_plus_clinical_partnerships", "founders_phd_count": "1",
        "founders_background": "汉雨生 (NJU + 哈佛 postdoc); MIT Tech Review 35 under 35",
        "founders_returnee": "1", "tech_dna": "clinical", "hardware_component": "paired_device",
        "us_counterpart": "Foundation Medicine / Guardant / Caris",
        "overseas_status": "planning", "overseas_target_regions": "SEA",
        "entry_paths": "public-co hire 广州",
        "nick_notes": "中国 NGS 头部. NASDAQ 退市边缘 (1:10 合股避险). 销售费用率 > 50% 一直亏损. 红旗 3/6 (估值倒挂 + SPAC 类压力 + 长期没新轮)",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Genetron Health", "name_zh": "世和基因",
        "segment": "S3", "subsegment": "oncology_ngs_lab",
        "founded_year": "2014", "hq_city": "Nanjing", "status": "private",
        "listing": "IPO_terminated_2024",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "200",
        "latest_round_date": "2022", "latest_round_type": "D",
        "revenue_usd_m": "70", "revenue_yoy_pct": "5",
        "payer_type": "hospital_plus_patient", "business_model": "per_test",
        "moat_type": "clinical_partnerships", "founders_phd_count": "1",
        "founders_background": "邵阳 PhD",
        "founders_returnee": "1", "tech_dna": "clinical", "hardware_component": "paired_device",
        "us_counterpart": "Foundation Medicine / Guardant",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "direct hire 南京",
        "nick_notes": "A 股 IPO 2024-Q4 主动撤单 失败. 销售费用率 ~50%. 比燃石小但同类问题",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Berry Genomics", "name_zh": "贝瑞和康",
        "segment": "S3", "subsegment": "prenatal_screening",
        "founded_year": "2010", "hq_city": "Beijing", "status": "public",
        "listing": "A_share_000710_SZSE",
        "latest_valuation_usd_m": "400", "total_funding_usd_m": "",
        "latest_round_date": "2017", "latest_round_type": "IPO_reverse_merger",
        "revenue_usd_m": "200", "revenue_yoy_pct": "10",
        "payer_type": "patient_plus_hospital", "business_model": "per_test",
        "moat_type": "scale", "founders_phd_count": "1",
        "founders_background": "周代星 (ex-Illumina + BGI)",
        "founders_returnee": "1", "tech_dna": "clinical", "hardware_component": "paired_device",
        "us_counterpart": "Natera",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 北京",
        "nick_notes": "中国产前 NIPT 头部. A 股上市. 北京家族业务直接同城",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "New Horizon Health", "name_zh": "诺辉健康",
        "segment": "S3", "subsegment": "colon_cancer_screening",
        "founded_year": "2015", "hq_city": "Hangzhou", "status": "public",
        "listing": "HK_6606_HK_trading_suspended_2024",
        "latest_valuation_usd_m": "500", "total_funding_usd_m": "250",
        "latest_round_date": "2021-02", "latest_round_type": "IPO",
        "revenue_usd_m": "120", "revenue_yoy_pct": "-30",
        "payer_type": "patient_plus_self_pay", "business_model": "per_screen_test",
        "moat_type": "regulatory_plus_brand", "founders_phd_count": "1",
        "founders_background": "朱叶青 PhD",
        "founders_returnee": "1", "tech_dna": "clinical", "hardware_component": "paired_device",
        "us_counterpart": "Exact Sciences Cologuard",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 杭州",
        "nick_notes": "常卫清 (Cologuard 中国版) 头部. 2024 起被传财务造假, HK 停牌. 红旗 5/6 极高风险",
        "data_as_of": "2026-05-16",
    },

    # S4 Drug Discovery AI (Insilico already in US table, cross-listed)
    {
        "name": "XtalPi", "name_zh": "晶泰科技",
        "segment": "S4", "subsegment": "ai_plus_quantum_drug_discovery",
        "founded_year": "2015", "hq_city": "Shenzhen", "status": "public",
        "listing": "HK_2228_HK",
        "latest_valuation_usd_m": "2000", "total_funding_usd_m": "700",
        "latest_round_date": "2024-06", "latest_round_type": "IPO",
        "revenue_usd_m": "30", "revenue_yoy_pct": "20",
        "payer_type": "big_pharma_partnership", "business_model": "partnership_milestone",
        "moat_type": "IP_plus_data", "founders_phd_count": "3",
        "founders_background": "温书豪 + 马健 + 赖力鹏 (MIT + Princeton PhDs)",
        "founders_returnee": "1", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Isomorphic Labs / Cradle Bio / Xaira",
        "overseas_status": "active", "overseas_target_regions": "US, EU",
        "entry_paths": "public-co hire 深圳 + 波士顿; 双总部 model 类似 Insilico",
        "nick_notes": "HK Ch 18A IPO 2024-06. 中港双总部 + AI + biotech. Insilico 之外另一个中国 AI drug discovery 旗舰",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Insilico Medicine (cross-ref)", "name_zh": "英矽智能",
        "segment": "S4", "subsegment": "gen_ai_drug_discovery",
        "founded_year": "2014", "hq_city": "Hong_Kong", "status": "public",
        "listing": "HK_3696_HK_Ch_8.05",
        "latest_valuation_usd_m": "2700", "total_funding_usd_m": "800",
        "latest_round_date": "2025-12", "latest_round_type": "IPO",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "big_pharma_partnership_plus_pipeline", "business_model": "milestone_plus_pipeline",
        "moat_type": "IP", "founders_phd_count": "1",
        "founders_background": "Alex Zhavoronkov PhD (JHU; Russia-born)",
        "founders_returnee": "0", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "(also in US companies.csv)",
        "overseas_status": "active",
        "overseas_target_regions": "已 multi-shore: SH+Suzhou+Boston+AbuDhabi+Montreal",
        "entry_paths": "direct hire 上海/苏州; ⭐ HK IPO 2025-12 范本",
        "nick_notes": "首个 HKEX Ch 8.05 AI biotech IPO. Phase 2 positive (rentosertib IPF). Nick 出海叙事直接范本",
        "data_as_of": "2026-05-16",
    },

    # S2 Clinical Decision Support / Medical LLM (中国巨头主导)
    {
        "name": "Bytedance Xiaohe AI Doctor", "name_zh": "字节小荷AI医生 / 豆包医疗",
        "segment": "S2", "subsegment": "consumer_medical_llm_app",
        "founded_year": "2025", "hq_city": "Beijing", "status": "private",
        "listing": "parent_Bytedance_private",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "",
        "latest_round_date": "2025-07", "latest_round_type": "internal_launch",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "consumer_plus_pharma_advertising", "business_model": "ad_supported_consumer_health",
        "moat_type": "scale_plus_brand", "founders_phd_count": "",
        "founders_background": "Bytedance internal team", "founders_returnee": "",
        "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "OpenEvidence (closest) / Hippocratic AI",
        "overseas_status": "planning", "overseas_target_regions": "follow Bytedance global",
        "entry_paths": "⭐ Nick Plan B (PM): 医疗产品经理 / 临床产品经理. 豆包大模型医疗 vertical 招聘活跃",
        "nick_notes": "字节 2025-07 launch 小荷AI医生 App. 基于豆包大模型 + 小荷医疗大模型. PM path 教科书匹配",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Alibaba Tongyi Medical", "name_zh": "阿里通义医疗 / 阿里健康",
        "segment": "S2", "subsegment": "ai_consumer_medical",
        "founded_year": "2014", "hq_city": "Hangzhou", "status": "public",
        "listing": "HK_0241_HK_Ali_Health",
        "latest_valuation_usd_m": "8000", "total_funding_usd_m": "",
        "latest_round_date": "2014", "latest_round_type": "IPO",
        "revenue_usd_m": "3500", "revenue_yoy_pct": "30",
        "payer_type": "consumer_plus_pharma", "business_model": "e_commerce_plus_ai_services",
        "moat_type": "scale_plus_distribution", "founders_phd_count": "",
        "founders_background": "Alibaba subsidiary mgmt",
        "founders_returnee": "", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Hims & Hers + OpenEvidence (hybrid)",
        "overseas_status": "planning", "overseas_target_regions": "SEA via Alibaba",
        "entry_paths": "public-co hire Hangzhou; ⭐ Nick Plan B (PM): AI 产品经理 / 海外业务 PM",
        "nick_notes": "阿里健康 HK 上市. 通义大模型医疗 vertical 集成. Lazada+SEA 出海可能",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Tencent Miying", "name_zh": "腾讯觅影",
        "segment": "S2+S5", "subsegment": "ai_imaging_plus_cds_in_tencent",
        "founded_year": "2017", "hq_city": "Shenzhen", "status": "private",
        "listing": "parent_Tencent_HK_0700",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "",
        "latest_round_date": "", "latest_round_type": "internal",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "hospital", "business_model": "internal_to_tencent_cloud",
        "moat_type": "platform_plus_brand", "founders_phd_count": "",
        "founders_background": "Tencent internal team",
        "founders_returnee": "", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Aidoc (imaging) + OpenEvidence (CDS)",
        "overseas_status": "planning", "overseas_target_regions": "SEA",
        "entry_paths": "⭐ Nick Plan C (PM): AI 影像产品经理 — S5 imaging + 腾讯生态 double match",
        "nick_notes": "腾讯医疗 AI 旗舰产品. 主要做胸片+病理+食管癌+宫颈癌 AI 筛查. Profile match 极高 for Nick (PM path)",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "JD Health Kangkang", "name_zh": "京东健康 / 康康 / 京医千询",
        "segment": "S2+S7", "subsegment": "consumer_medical_ai",
        "founded_year": "2019", "hq_city": "Beijing", "status": "public",
        "listing": "HK_6618_HK",
        "latest_valuation_usd_m": "12000", "total_funding_usd_m": "",
        "latest_round_date": "2020-12", "latest_round_type": "IPO",
        "revenue_usd_m": "6000", "revenue_yoy_pct": "25",
        "payer_type": "consumer", "business_model": "e_commerce_plus_telehealth_plus_ai",
        "moat_type": "scale", "founders_phd_count": "",
        "founders_background": "JD subsidiary",
        "founders_returnee": "", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Hims & Hers + Ro (D2C Rx)",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 北京; AI 产品经理 / 互联网医院 PM",
        "nick_notes": "HK 上市 $12B 市值. 接入 DeepSeek + 自研京医千询 + 康康 agent. 北京家族业务同城",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Ping An Healthcare", "name_zh": "平安好医生",
        "segment": "S7+S2", "subsegment": "ai_telehealth",
        "founded_year": "2014", "hq_city": "Shanghai", "status": "public",
        "listing": "HK_1833_HK",
        "latest_valuation_usd_m": "1500", "total_funding_usd_m": "",
        "latest_round_date": "2018-05", "latest_round_type": "IPO",
        "revenue_usd_m": "700", "revenue_yoy_pct": "5",
        "payer_type": "consumer_plus_insurance", "business_model": "insurance_bundled_telehealth",
        "moat_type": "scale_plus_insurance_distribution", "founders_phd_count": "",
        "founders_background": "Ping An subsidiary", "founders_returnee": "",
        "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "K Health + Spring Health",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 上海",
        "nick_notes": "HK 上市但市值跌至 $1.5B (曾 $10B+). 红旗 4/6 估值倒挂. 不推荐",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "Ant AQ Afu", "name_zh": "蚂蚁阿福 / 蚂蚁医疗大模型",
        "segment": "S2", "subsegment": "consumer_medical_llm_app",
        "founded_year": "2025", "hq_city": "Hangzhou", "status": "private",
        "listing": "parent_Ant_Group_private",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "",
        "latest_round_date": "2025-06", "latest_round_type": "internal_launch",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "consumer_plus_insurance", "business_model": "ad_plus_premium_subscription",
        "moat_type": "platform_distribution_via_Alipay", "founders_phd_count": "",
        "founders_background": "Ant Group internal team", "founders_returnee": "",
        "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "OpenEvidence / Hippocratic AI",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "direct hire 杭州; AI 医疗产品经理",
        "nick_notes": "2025-06 launch 蚂蚁 AQ -> 改名蚂蚁阿福. 蚂蚁集团把 AI 医疗推为潜在主业",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "DeepSeek Medical (potential)", "name_zh": "DeepSeek 医疗方向",
        "segment": "S2", "subsegment": "general_llm_medical_vertical",
        "founded_year": "2023", "hq_city": "Hangzhou", "status": "private",
        "listing": "parent_DeepSeek_private",
        "latest_valuation_usd_m": "", "total_funding_usd_m": "",
        "latest_round_date": "", "latest_round_type": "",
        "revenue_usd_m": "", "revenue_yoy_pct": "",
        "payer_type": "api_consumers_plus_enterprise", "business_model": "api_pricing",
        "moat_type": "model_capability", "founders_phd_count": "1",
        "founders_background": "梁文锋",
        "founders_returnee": "0", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "(no direct US analog - independent foundation model)",
        "overseas_status": "active", "overseas_target_regions": "global API",
        "entry_paths": "direct hire 杭州; 应用层 PM 招聘可能性",
        "nick_notes": "DeepSeek 自身是 LLM lab 不是医疗 vertical. 但 京东健康 已接入. 可能未来发医疗 vertical",
        "data_as_of": "2026-05-16",
    },

    # S6 RCM / Admin AI (Chinese hospital IT vendors)
    {
        "name": "Winning Health", "name_zh": "卫宁健康",
        "segment": "S6", "subsegment": "hospital_information_system_plus_ai",
        "founded_year": "1994", "hq_city": "Shanghai", "status": "public",
        "listing": "A_share_300253_SZSE",
        "latest_valuation_usd_m": "1500", "total_funding_usd_m": "",
        "latest_round_date": "2011", "latest_round_type": "IPO",
        "revenue_usd_m": "400", "revenue_yoy_pct": "5",
        "payer_type": "hospital", "business_model": "his_software_plus_ai_modules",
        "moat_type": "scale_plus_distribution", "founders_phd_count": "0",
        "founders_background": "周炜 (founder, non-PhD)",
        "founders_returnee": "0", "tech_dna": "clinical", "hardware_component": "none",
        "us_counterpart": "Epic / Cerner + Innovaccer (closest)",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 上海",
        "nick_notes": "中国 HIS (医院信息系统) 头部. AI 模块为增量. 不像美国 Innovaccer 是 AI-native, 卫宁是 legacy 软件 + 加 AI",
        "data_as_of": "2026-05-16",
    },
    {
        "name": "B-Soft", "name_zh": "创业慧康",
        "segment": "S6", "subsegment": "hospital_information_system",
        "founded_year": "1997", "hq_city": "Hangzhou", "status": "public",
        "listing": "A_share_300451_SZSE",
        "latest_valuation_usd_m": "800", "total_funding_usd_m": "",
        "latest_round_date": "2015", "latest_round_type": "IPO",
        "revenue_usd_m": "200", "revenue_yoy_pct": "5",
        "payer_type": "hospital", "business_model": "his_software",
        "moat_type": "scale", "founders_phd_count": "0",
        "founders_background": "葛航 (founder)",
        "founders_returnee": "0", "tech_dna": "clinical", "hardware_component": "none",
        "us_counterpart": "Cerner / Allscripts",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "public-co hire 杭州",
        "nick_notes": "中国 HIS 第二档. 比卫宁略小",
        "data_as_of": "2026-05-16",
    },

    # S7 (Hims/Ro China analog - mostly e-commerce health)
    # JD Health, Ali Health, Ping An already covered above (cross-segment S2+S7)
    # Add only 微医
    {
        "name": "We Doctor", "name_zh": "微医",
        "segment": "S7", "subsegment": "ai_telehealth_internet_hospital",
        "founded_year": "2010", "hq_city": "Hangzhou", "status": "private",
        "listing": "HK_IPO_postponed_2021",
        "latest_valuation_usd_m": "5000", "total_funding_usd_m": "1500",
        "latest_round_date": "2021", "latest_round_type": "F",
        "revenue_usd_m": "200", "revenue_yoy_pct": "10",
        "payer_type": "patient_plus_insurance_plus_govt", "business_model": "telehealth_subscription_plus_insurance",
        "moat_type": "scale_plus_govt_relations", "founders_phd_count": "1",
        "founders_background": "廖杰远",
        "founders_returnee": "0", "tech_dna": "hybrid", "hardware_component": "none",
        "us_counterpart": "Teladoc + K Health",
        "overseas_status": "none", "overseas_target_regions": "",
        "entry_paths": "direct hire 杭州",
        "nick_notes": "HK IPO 2021 推迟至今未完成. 估值降至 $5B (曾 $7B+). 红旗 3/6",
        "data_as_of": "2026-05-16",
    },

    # S1 China Clinical Documentation (weak segment in China but exists)
    {
        "name": "Unisound", "name_zh": "云知声",
        "segment": "S1+S2", "subsegment": "medical_voice_plus_llm",
        "founded_year": "2012", "hq_city": "Beijing", "status": "public",
        "listing": "HK_9678_HK_2025",
        "latest_valuation_usd_m": "1000", "total_funding_usd_m": "300",
        "latest_round_date": "2025-04", "latest_round_type": "IPO",
        "revenue_usd_m": "100", "revenue_yoy_pct": "20",
        "payer_type": "hospital_plus_enterprise", "business_model": "voice_ai_solution",
        "moat_type": "tech_plus_brand", "founders_phd_count": "1",
        "founders_background": "黄伟 PhD",
        "founders_returnee": "0", "tech_dna": "algorithm", "hardware_component": "none",
        "us_counterpart": "Nuance (medical voice)",
        "overseas_status": "planning", "overseas_target_regions": "SEA",
        "entry_paths": "public-co hire 北京",
        "nick_notes": "中国医疗语音 AI + LLM (山海大模型). HK 2025-04 IPO. 是中国最接近 Nuance 模式的厂",
        "data_as_of": "2026-05-16",
    },
]


def main():
    # Read existing header
    with CSV.open("r", encoding="utf-8") as f:
        header = next(csv.reader(f))
    # Append rows
    with CSV.open("a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=header)
        for row in ROWS:
            # fill any missing keys with empty string
            for k in header:
                row.setdefault(k, "")
            w.writerow(row)
    print(f"Appended {len(ROWS)} China companies. CSV now has header + {len(ROWS)} new data rows.")


if __name__ == "__main__":
    main()
